-- =========================================================================
-- CENTRALIZAÇÃO DE PROTOCOLO E SINCRONIZAÇÃO DE CONVERSAS
-- =========================================================================

-- 1. Criação da SEQUENCE para protocolos (Ano + 6 dígitos)
-- Nota: Começamos em 1, mas a função formatará como 000001
CREATE SEQUENCE IF NOT EXISTS protocol_seq START 1;

-- 2. Função padronizada para obter o próximo protocolo
CREATE OR REPLACE FUNCTION fn_get_next_protocol()
RETURNS TEXT AS $$
DECLARE
    current_year TEXT;
    seq_val BIGINT;
BEGIN
    current_year := to_char(CURRENT_DATE, 'YYYY');
    seq_val := nextval('protocol_seq');
    RETURN current_year || lpad(seq_val::TEXT, 6, '0');
END;
$$ LANGUAGE plpgsql;

-- 3. Tabela conversas_ativas (conforme fornecido pelo usuário)
CREATE TABLE IF NOT EXISTS public.conversas_ativas (
  id bigint generated by default as identity not null,
  protocolo text not null,
  remotejid character varying null,
  anonimo boolean not null default false,
  nome character varying null,
  cpf character varying null,
  telefone character varying null,
  email character varying null,
  tipo_manifestacao character varying null,
  area character varying null,
  assunto character varying null,
  demanda text null,
  status character varying not null default 'PRE_CADASTRO'::character varying,
  created_at timestamp with time zone not null default now(),
  constraint conversas_ativas_pkey primary key (id)
);

-- 4. Função para sincronizar Conversa -> Demandas
CREATE OR REPLACE FUNCTION sync_conversa_to_demands()
RETURNS TRIGGER AS $$
DECLARE
    v_organ_id UUID;
BEGIN
    -- Só sincroniza se o status mudar de PRE_CADASTRO para CONCLUIDO (ou outro status de finalização)
    -- Adicionamos uma trava para garantir que a demanda não seja criada duas vezes
    IF (OLD.status = 'PRE_CADASTRO' AND NEW.status = 'CONCLUIDO') THEN
        
        -- Verifica se já não existe uma demanda com este protocolo para evitar duplicidade
        IF EXISTS (SELECT 1 FROM demands WHERE protocol = NEW.protocolo) THEN
            RETURN NEW;
        END IF;

        -- Busca um órgão padrão ou tenta mapear pela "area"
        SELECT id INTO v_organ_id FROM organs WHERE acronym = NEW.area LIMIT 1;
        IF v_organ_id IS NULL THEN
            SELECT id INTO v_organ_id FROM organs WHERE status = 'ativo' LIMIT 1;
        END IF;

        INSERT INTO demands (
            protocol,
            type,
            status,
            priority,
            organ_id,
            description,
            channel,
            anonymous,
            citizen_name,
            citizen_cpf,
            citizen_phone,
            citizen_email,
            deadline
        ) VALUES (
            NEW.protocolo,
            COALESCE(LOWER(NEW.tipo_manifestacao), 'solicitacao'),
            'registrada',
            'media',
            v_organ_id,
            NEW.demanda,
            'whatsapp',
            NEW.anonimo,
            NEW.nome,
            NEW.cpf,
            NEW.telefone,
            NEW.email,
            NOW() + interval '20 days'
        );
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- 5. Função para gerar protocolo antes de inserir na conversas_ativas
CREATE OR REPLACE FUNCTION trg_fn_generate_conversa_protocol()
RETURNS TRIGGER AS $$
BEGIN
    IF NEW.protocolo IS NULL OR NEW.protocolo = '' THEN
        NEW.protocolo := fn_get_next_protocol();
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- 6. Triggers para conversas_ativas
DROP TRIGGER IF EXISTS trg_before_insert_conversa ON conversas_ativas;
CREATE TRIGGER trg_before_insert_conversa
BEFORE INSERT ON conversas_ativas
FOR EACH ROW
EXECUTE FUNCTION trg_fn_generate_conversa_protocol();

DROP TRIGGER IF EXISTS trg_sync_conversas_demands ON conversas_ativas;
CREATE TRIGGER trg_sync_conversas_demands
AFTER UPDATE ON conversas_ativas
FOR EACH ROW
EXECUTE FUNCTION sync_conversa_to_demands();

-- 7. Atualizar a trigger da tabela demands para usar a mesma lógica
CREATE OR REPLACE FUNCTION generate_demand_protocol()
RETURNS TRIGGER AS $$
BEGIN
    -- Se o protocolo já vem preenchido (vinda da sync_conversa), não gera novo
    IF NEW.protocol IS NULL OR NEW.protocol = '' THEN
        NEW.protocol := fn_get_next_protocol();
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;
